### ISSUE TITLE
jstoolbar doesn't show up whit redmine 2.0.3

### ISSUE THREAD

**Issue by frankmorris** [alminium/redmine_redcarpet_formatter#10]
jstoolbar doesn't show up whit redmine 2.0.3

so I modify the redmine_redcarpet_formatter/lib/redmine/wiki_formatting/markdown/helper.rb 

change 
`var toolbar = new jsToolBar($('#{field_id}'));`

to
`var toolbar = new jsToolBar(document.getElementById('#{field_id}'));`

then it wokrs. Please update your code. Thanks, and I love this plugin.

**Comment by mikoto20000** [comment]
Thank you for your feedback.

Unfortunately, it seems work on my environment(Redmine 2.0.3).

jstoolbar showed up on wiki and ticket. Which page did you have the problem?
And what browser do you use?

**Comment by frankmorris** [comment]
I have this problem on every wiki toolbar page. It happens on chrome Version 21.0.1180.79, Safari Version 6.0 (8536.25)

**Comment by mikoto20000** [comment]
I could not reproduce the problem. But you have the problem in the fact.

I think your propose not affect others.I applied your propose 

Thanks.
