### ISSUE TITLE
Missing formatting toolbar with Redmine 2.1.2

### ISSUE THREAD

**Issue by chronon** [alminium/redmine_redcarpet_formatter#13]
The formatting toolbar and help pop-up link are completely missing with Redmine 2.1.2.

**Comment by lpar** [comment]
I don't consider that a bug :-)

I don't need a formatting toolbar for Markdown, and implementing one could be a lot of work. A help link might be nice though.

**Comment by chronon** [comment]
Yeah, I don't need a toolbar either, but a user reported it missing on my Redmine installation after an upgrade. I believe an older, no longer maintained Markown formatter I used to use had a toolbar...which (incorrectly) led me to believe it was missing from this one.

**Comment by stricker** [comment]
We are missing the toolbar very much after upgrading to 2.1.2 & would hope for a fix. :+1:

**Comment by mikoto20000** [comment]
Sorry, not sooner reply. I checked Redmine 2.1.2 and redcarpet wiki formatter head. Actually toolbar seems work.
How doesn't it work?

**Comment by stricker** [comment]
That's strange. We will check & see what's wrong at our end. Thanks!

**Comment by chronon** [comment]
It's still not working for me (Redmine 2.1.2). Setting "text formatting" in Administration -> settings to "textile" gives me a toolbar when creating a new issue:

![textile](https://dl.dropbox.com/u/41775/textile.jpg).

If I change it to "markdown", the toolbar is gone (but markdown formatting works):

![markdown](https://dl.dropbox.com/u/41775/markdown.jpg).

**Comment by stricker** [comment]
I think it may be a front-end issue. Rails production.log is clean, but I get consistently a JavaScript error on Safari, Firefox and Chrome:
`TypeError: 'undefined' is not an object (evaluating 'this.toolbar.hasChildNodes') in jstoolbar.js:205`
Continue investigating ...

**Comment by mikoto20000** [comment]
I checked Issue tracker but the toolbar was appeared. 
Have you installed any issue related plugins?

**Comment by chronon** [comment]
This is the only plugin I have installed.

**Comment by stricker** [comment]
This is my complete environment information:

```
Environment:
   Redmine version                          2.1.2.stable
   Ruby version                             1.9.3 (x86_64-linux)
   Rails version                            3.2.8
   Environment                              production
   Database adapter                         Mysql2
Redmine plugins:
   redmine_auto_percent                     0.0.1
   redmine_etherpad                         0.0.1
   redmine_plugin_views_revisions           0.0.1
   redmine_redcarpet_formatter              2.0.1
   redmine_smart_issues_sort                0.3.1
```

`

**Comment by stricker** [comment]
Found it. Had to apply manually this fix: alminium@8a32a06dc6db53bb92e5c555ae5d7b54016b33e4
Thanks to all!

**Comment by chronon** [comment]
The fix doesn't work for me, still no toolbar.

**Comment by mikoto20000** [comment]
chronon,

> This is the only plugin I have installed.

Me too. But work for me.
What browser did you have problem?

**Comment by mikoto20000** [comment]
chronon, 

I have another question. Was the toolbar showed on Wiki editing page?

**Comment by chronon** [comment]
I've tested with Chrome 23, Safari 6, and Firefox 16 (all on OS X 10.8), but haven't had a chance to test with Windows yet. I don't see the toolbar on the Wiki editing page (or on the project description page).

**Comment by mikoto20000** [comment]
I tested Firefox 16.0.2, IE9 , Chrome  23.0.1271.64 on Windows but worked.

Did you have any JavaScript error? In chrome case, press F12 key to show developer tool and select Console Tab.

**Comment by chronon** [comment]
I just tested with IE9 on Windows 7 and still no toolbar. 

JavaScript console **does** have an error:

`Uncaught TypeError: Cannot call method 'hasChildNodes' of undefined    jstoolbar.js:205
jsToolBar.draw     jstoolbar.js:205
(anonymous function)     new:110`

**Comment by mikoto20000** [comment]
Your plugin seems old.  Please run following command in your redmine_redcarpet_formatter folder.

```
 $ git checkout master
 $ git show -s HEAD
```

It must show 

```
commit 79f9656cea45ec2b140a5078ab802b0f9fd26757
```

**Comment by chronon** [comment]
I was on the redmine-2.0.x branch.

Switching to master and restarting Redmine causes Redmine to not start with error message "no such file to load -- redcarpet". I have redcarpet 2.2.2 installed, so I don't know what the problem is, but it sounds like it's something on my end and not in your plugin. Thanks for the help.

**Comment by whittaker007** [comment]
I'm having this issue with redmine_redcarpet_formatter v2.0.1 (the current master head) on Redmine 2.4.2.stable and Ruby 1.9.3-p484
