### ISSUE TITLE
Strikeout & Underlining break links

### ISSUE THREAD

**Issue by danomatika** [alminium/redmine_redcarpet_formatter#19]
Using <del> & <ins> tags around links like:

```
<del>[Pagescroller single page template for $35](http://pagescroller.com/)</del>
```

Result in the text being struckout but the link is not being evaluated. The original textile formatter in Redmine, however, still sets the hyperlinks for the same formatting options.

**Comment by mikoto20000** [comment]
redcarpet formatter uses redcarpet is used in GitHub markdown.
Unfortunately, your report is same as GitHub's markdown.

Could you report to redcarpet repository https://github.com/vmg/redcarpet ?
