### ISSUE TITLE
Links with closed parens boken

### ISSUE THREAD

**Issue by danomatika** [alminium/redmine_redcarpet_formatter#20]
Using a link like this:

`http://en.wikipedia.org/wiki/Nightfall_(Asimov_short_story)`

in a markdown link like:

`[Nightfall](http://en.wikipedia.org/wiki/Nightfall_(Asimov_short_story))`

is not rendered correctly as the first close parens is used to close the link, instead of the second parens. The rendered link is:

`http://en.wikipedia.org/wiki/Nightfall_(Asimov_short_story`

which is broken. I think the parser needs to use a stack to remember if a closed parens was found in the link it self ...

**Comment by mikoto20000** [comment]
redcarpet formatter uses redcarpet is used in GitHub markdown.
Unfortunately, your report is same as GitHub's markdown.

Could you report to redcarpet repository https://github.com/vmg/redcarpet ?

**Comment by danomatika** [comment]
Apparently it's up the the user to escape the parens in this case as per the Markdown spec: https://github.com/vmg/redcarpet/issues/45

:P Too bad. Escaping the parens with a backslash works. Like this:

`[Nightfall](http://en.wikipedia.org/wiki/Nightfall_\(Asimov_short_story\))`
