### ISSUE TITLE
attachment link with underscores dosen't work

### ISSUE THREAD

**Issue by danomatika** [alminium/redmine_redcarpet_formatter#21]
An attachment file like this:

`an_attachment_file.pdf`

dosen't work with the attachment keyword:

`attachment:an_attachment_file.pdf`

as the underscores are interpretted as emphasis marks.

The markdown parser should not be invoked when using `attachment:`.

**Comment by mikoto20000** [comment]
Thanks for your report.

I fixed it in master.

best regards,

**Comment by danomatika** [comment]
Actually I may be wrong on this. The [markdown syntax page](http://daringfireball.net/projects/markdown/syntax#em) says you should be able to place emphasis inside words. If you want literal \* or _ you have to escpae the chars manually with backslashes.

I tried this with `attachment:` and it does work, although seems weird:

`attachment:an\_attachment\_file.pdf`

Either way, up to you.

**Comment by danomatika** [comment]
Also, to note, PHP Markdown does _not_ evaluate [emphasis inside words](http://michelf.ca/projects/php-markdown/extra/#em).

**Comment by mikoto20000** [comment]
I tested GitHub's wiki. It ignored internal emphasis.

I would like to keep compatible GitHub Markdown.

**Comment by danomatika** [comment]
Yeah. I agree with standardizing to GH. Thanks.
