### ISSUE TITLE
section edit got "500 Internal Server Error"

### ISSUE THREAD

**Issue by missedone** [alminium/redmine_redcarpet_formatter#23]
here i found a bug when i click the "Edit this section" icon on the wiki page.
(see attached screenshot please)
i got the "500 Internal Server Error"

seek in the production.log, there are lines relate to the error:

```
NoMethodError (undefined method `each' for #<String:0xcdc790c>):
  app/controllers/wiki_controller.rb:125:in `edit'
```

i have Redmine 2.2.3 installed, and redmine_redcarpet_formatter plugin for the Markdown Wiki formatter.

**Comment by lammel** [comment]
A fix for this issue has been merged some time ago, please verify if this might be the issue:

https://github.com/alminium/redmine_redcarpet_formatter/pull/8

**Comment by missedone** [comment]
Oh, yes, i was using the tag 2.0.1, not aware of it has already been fixed on master branch, sorry for duplication.

thanks
