### ISSUE TITLE
"help" link disappear

### ISSUE THREAD

**Issue by cmwinner** [alminium/redmine_redcarpet_formatter#25]
i can not find the "help" link.

**Comment by mikoto20000** [comment]
Which version of redmine did you use?
I checked with Redmine 2.2.4. It worked.

**Comment by cmwinner** [comment]
the latest version 2.3.0

**Comment by mikoto20000** [comment]
Fixed. Please try master HEAD.

**Comment by cmwinner** [comment]
It doesn't work yet.

**Comment by mikoto20000** [comment]
Sorry, I missed to commit javascript. It should be fixed now.

**Comment by cmwinner** [comment]
ok, it works.
