### ISSUE TITLE
redcarpet 2.1.0がダウンロード出来ました

### ISSUE THREAD

**Issue by drakontia** [alminium/redmine_redcarpet_formatter#3]
こんにちわ。
redcarpetのgemのリンクが復活しているようです。
http://rubygems.org/gems/redcarpet

Mac環境ですが、gem install redcarpetでインストールして、
redmine_redcarpet_formatterも動いていることを確認しました。

お気づきかもしれませんが、ご一報までに。

**Comment by mikoto20000** [comment]
ありがとうございます。オリジナルのRedcarpetは不具合があり、修正を加えて利用してます。

よろしくお願いします。
