### ISSUE TITLE
Support Redmine 2.5.x

### ISSUE THREAD

**Issue by mather** [alminium/redmine_redcarpet_formatter#34]
Redmine 2.5.x officially supported Markdown Wiki format as experimental feature.
So, Redcarpet Formatter plugin conflicts against this feature.
- conflict : `wiki_format_provider "markdown"` on `init.rb`
- conflict : `Redmine::WikiFormatting::Markdown` module

Rename to `RedcarpetMarkdown` or something else.

**Comment by mikoto20000** [comment]
I have been providing Redcarpet Formtter before 2.5.0 released.
I think redmine 2.5 should rename them, not our responsibility.

**Comment by mather** [comment]
Right.

**Comment by marcaudefroy** [comment]
I have the same issue. How I can solve this problem?

**Comment by mather** [comment]
I recommend to use Redmine 2.4.x until markdown formatter is experimental in Redmine 2.5.x.
Or else apply patch to formatter at your own risk.
Here is my sample code http://qiita.com/mather314/items/79e082bf4f9f9300c0a9 (Japanese site)
