### ISSUE TITLE
missing copyright/license information

### ISSUE THREAD

**Issue by onlyjob** [alminium/redmine_redcarpet_formatter#9]
Hi, 

Thank you for a fantastic plugin. 
Markdown functionality for Redmine is much appreciated.

Unfortunately at the moment it is not possible to package your work for GNU/Linux distributions due to missing copyright and licensing information.

Would it be possible to attach copyright statement with decent copyleft license like GPL-2+ or even GPL-3+ please?

I hope this would be easy to do.

Thank you.

Regards,
Dmitry.

**Comment by mikoto20000** [comment]
Excuse me, not sooner reply. I included GPLv2 License file.

thanks.

**Comment by frankmorris** [comment]
thanks, i love this plugin

**Comment by onlyjob** [comment]
Thank you but this requires just a little bit more of your attention:
- Who is the copyright holder specifically?
- Years of copyright should be included to copyright statement to make it valid.
- What is the license version exactly? GPL-2 or GPL-2+?
- Ideally all the above should be stated somewhere like RELEASE-NOTES or in file headers if license is applicable only to some but not all files.

Also you included incomplete text of the license. 
Usually in the end of the license there is information how to apply it (as below). 
Please follow the instructions if possible.

Thank you.

Regards,
Dmitry.

# 

```
        How to Apply These Terms to Your New Programs
```

  If you develop a new program, and you want it to be of the greatest
possible use to the public, the best way to achieve this is to make it
free software which everyone can redistribute and change under these terms.

  To do so, attach the following notices to the program.  It is safest
to attach them to the start of each source file to most effectively
convey the exclusion of warranty; and each file should have at least
the "copyright" line and a pointer to where the full notice is found.

```
<one line to give the program's name and a brief idea of what it does.>
Copyright (C) <year>  <name of author>

This program is free software; you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation; either version 2 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License along
with this program; if not, write to the Free Software Foundation, Inc.,
51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
```

**Comment by mikoto20000** [comment]
I added some license description at 'license' branch. Could you check  it?

regards,

**Comment by onlyjob** [comment]
On Tue, 21 Aug 2012 11:57:02 mikoto20000 wrote:

> I added some license description at 'license' branch. Could you check  it?

It is very good now, thank you. :)

Also you might want to add your email like myemail@github.com
after your name in copyright statement line - something like 

   Copyright (C) 2012 Takashi Okamoto myemail@github.com

As far as I'm aware '(C)' no longer required by copyright law since 
ratification of Berne convention in 1988. 
Word 'Copyright' should be enough but it won't hurt to follow license 
instructions how to apply since they still recommend to include '(C)'.

Thank you very much for correcting this. 
I will be packaging your work for Debian soon. :)

Regards,
Dmitry.
